"""drop fraud_score from transactions, add fraud_scores table

Revision ID: 0b93d2339ea6
Revises: 995e09112c6c
Create Date: 2026-08-18 17:20:06.456720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b93d2339ea6'
down_revision: Union[str, Sequence[str], None] = '995e09112c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fraud_scores',
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('fraud_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    op.drop_column('transactions', 'fraud_score')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('fraud_score', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=False))
    op.drop_table('fraud_scores')
    # ### end Alembic commands ###
