"""create accounts merchants transactions tables

Revision ID: 6119b6014156
Revises: 549450b7f940
Create Date: 2026-08-01 20:26:35.606581

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '6119b6014156'
down_revision: str | Sequence[str] | None = '549450b7f940'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
