FROM python:3.12-slim

WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN pip install poetry
RUN poetry config virtualenvs.create false \
    && poetry install --no-ansi --no-root

COPY src ./src
COPY config ./config

CMD ["python", "src/main.py"]