FROM python:3.12-slim

WORKDIR /app 

RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY pyproject.toml poetry.lock ./

RUN pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install --no-ansi --no-root

COPY src ./src
COPY config ./config
COPY alembic.ini ./
COPY alembic ./alembic

ENV PYTHONPATH=/app/src

CMD ["alembic", "upgrade", "head"]